#!/usr/bin/env python3
"""overlap-classifier Agent の出力を受け取り、クラスタごとに GitHub Issue を起票する。

冪等性: ~/.cache/overlap-audit/posted.json に cluster_id を記録し、
        同一 cluster_id は重複起票しない（--force で上書き可能）。
"""

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path


def _detect_repo() -> str:
    """gh CLI でカレントリポジトリの nameWithOwner を取得する。失敗時はフォールバック値を返す."""
    try:
        return subprocess.check_output(
            [  # noqa: S607
                "gh",
                "repo",
                "view",
                "--json",
                "nameWithOwner",
                "-q",
                ".nameWithOwner",
            ],
            text=True,
            stderr=subprocess.DEVNULL,
            timeout=10,
        ).strip()
    except Exception:
        return "UtakataKyosui/C2Lab"


REPO = _detect_repo()
CACHE_DIR = Path.home() / ".cache" / "overlap-audit"
POSTED_FILE = CACHE_DIR / "posted.json"
LABEL_OVERLAP = "audit/overlap"
LABEL_AUTO = "auto-generated"
MAX_ISSUES_PER_RUN = 20


def _load_posted() -> dict[str, str]:
    if not POSTED_FILE.is_file():
        return {}
    try:
        return json.loads(POSTED_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _save_posted(records: dict[str, str]) -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    POSTED_FILE.write_text(json.dumps(records, indent=2), encoding="utf-8")


def _build_issue_body(cluster: dict) -> str:
    """classified_clusters の 1 要素から Issue 本文 Markdown を生成する."""
    # Agent が issue_body を生成済みの場合はそのまま使う
    if cluster.get("issue_body"):
        return cluster["issue_body"]

    # Agent 未評価クラスタの fallback 本文
    members = cluster.get("members", [])
    verdict = cluster.get("verdict", "review")
    category = cluster.get("category", "unknown")
    cluster_id = cluster.get("cluster_id", "")
    rationale = cluster.get("rationale", "（自動分類未実施）")
    keep = cluster.get("recommended_keep", {})
    drops = cluster.get("drop_candidates", [])

    rows = "\n".join(
        f"| {i + 1} | {m['name']} | {m['kind']} | {m['source']} "
        f"| {m.get('plugin', '')} | {m.get('description', '')[:80]} |"
        for i, m in enumerate(members)
    )
    header = "| # | name | kind | source | plugin | description |\n|---|------|------|--------|--------|-------------|"
    table = f"{header}\n{rows}"

    keep_line = (
        f"- [ ] **keep**: `{keep.get('path', keep.get('id', ''))}` — {keep.get('name', '')}"
        if keep
        else "- [ ] **keep**: （未判定）"
    )
    drop_lines = "\n".join(
        f"- [ ] **drop**: `{d.get('path', d.get('id', ''))}` — {d.get('reason', '')}"
        for d in drops
    )
    if not drop_lines:
        drop_lines = "- [ ] **drop**: （未判定）"

    date_str = datetime.now().strftime("%Y-%m-%d")
    return f"""## 概要

**カテゴリ**: {category}
**クラスタ ID**: {cluster_id}
**判定**: {verdict}

## メンバー一覧

{table}

## 推奨アクション

{keep_line}
{drop_lines}
- [ ] **coexist**: 両方残す（判定根拠と理由を明記してください）

## 判定根拠

{rationale}

## 関連

- [overlap-policy](https://github.com/{REPO}/blob/main/plugins/plugin-overlap-auditor/skills/overlap-policy/SKILL.md)
- Generated by `/audit-overlap` on {date_str}
"""


def _ensure_labels() -> None:
    """必要なラベルが存在しなければ作成する."""
    for label, color, desc in [
        (LABEL_OVERLAP, "e4e669", "Skill/Agent/Command の役割重複"),
        (LABEL_AUTO, "bfd4f2", "自動生成された Issue"),
    ]:
        subprocess.run(  # noqa: S603
            [  # noqa: S607
                "gh",
                "label",
                "create",
                label,
                "--repo",
                REPO,
                "--color",
                color,
                "--description",
                desc,
                "--force",
            ],
            capture_output=True,
            check=False,
        )


def post_cluster_issue(cluster: dict, *, dry_run: bool = False) -> dict:
    """1 クラスタ分の Issue を起票する."""
    cluster_id = cluster.get("cluster_id", "unknown")
    title = cluster.get("issue_title") or (
        f"[overlap-audit] {cluster.get('category', 'unknown')}: "
        + " / ".join(m["name"] for m in cluster.get("members", [])[:4])
    )
    body = _build_issue_body(cluster)

    tmp_path = CACHE_DIR / f"body-{cluster_id}.md"
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    tmp_path.write_text(body, encoding="utf-8")

    cmd = [
        "gh",
        "issue",
        "create",
        "--repo",
        REPO,
        "--title",
        title,
        "--body-file",
        str(tmp_path),
        "--label",
        LABEL_OVERLAP,
        "--label",
        LABEL_AUTO,
    ]

    if dry_run:
        return {
            "dry_run": True,
            "cluster_id": cluster_id,
            "title": title,
            "body_preview": body[:500],
            "would_run": " ".join(cmd),
        }

    for attempt in range(2):
        result = subprocess.run(  # noqa: S603
            cmd, capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            return {"success": True, "cluster_id": cluster_id, "url": url}
        if attempt == 0:
            time.sleep(2)

    return {
        "success": False,
        "cluster_id": cluster_id,
        "error": result.stderr.strip(),
        "draft_path": str(tmp_path),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="overlap-classifier 出力からクラスタごとに GitHub Issue を起票する"
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="-",
        help="classified_clusters JSON。- で標準入力 (デフォルト: -)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="実際には起票せず内容を表示する"
    )
    parser.add_argument(
        "--force", action="store_true", help="起票済みクラスタも再起票する"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=MAX_ISSUES_PER_RUN,
        help=f"1 回の実行で起票する最大件数 (デフォルト: {MAX_ISSUES_PER_RUN})",
    )
    args = parser.parse_args()

    if args.input == "-":
        raw = sys.stdin.read()
    else:
        raw = Path(args.input).read_text(encoding="utf-8")

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"[post_overlap_issues] ERROR: JSON parse failed: {e}", file=sys.stderr)
        sys.exit(1)

    clusters = data.get("classified_clusters", data.get("clusters", []))
    if not clusters:
        print("[post_overlap_issues] クラスタが見つかりませんでした。", file=sys.stderr)
        sys.exit(0)

    posted = _load_posted()

    if not args.dry_run:
        _ensure_labels()

    results = []
    count = 0
    for cluster in clusters:
        if count >= args.limit:
            print(
                f"[post_overlap_issues] --limit={args.limit} に達したため残りをスキップ",
                file=sys.stderr,
            )
            break
        cid = cluster.get("cluster_id", "unknown")
        if not args.force and cid in posted:
            print(
                f"[post_overlap_issues] SKIP (already posted): {cid}", file=sys.stderr
            )
            continue

        result = post_cluster_issue(cluster, dry_run=args.dry_run)
        results.append(result)
        count += 1

        if result.get("dry_run"):
            print(f"\n--- DRY-RUN: {result['cluster_id']} ---")
            print(f"Title: {result['title']}")
            print(result["body_preview"])
        elif result.get("success"):
            print(f"[post_overlap_issues] Posted: {result['url']}")
            posted[cid] = result["url"]
            _save_posted(posted)
        else:
            print(
                f"[post_overlap_issues] FAILED: {cid}: {result.get('error')}",
                file=sys.stderr,
            )

    print(
        f"\n[post_overlap_issues] 完了: {count} 件処理",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
