#!/usr/bin/env python3
"""Generate a dry-run report from triage output and post it as a PR comment.

Posts a markdown table showing what auto-pr-responder WOULD do, without
actually making any code changes or posting replies to threads.

Uses `gh pr comment` intentionally here — this is a top-level summary comment,
not a threaded reply. This is the ONLY place `gh pr comment` is permitted in
this plugin.
"""

import json
import subprocess
import sys
from pathlib import Path

CATEGORY_ICONS = {
    "valid-fix": "✅ 修正+返信",
    "invalid-reject": "❌ 返信のみ（却下）",
    "needs-human": "⏸️ スキップ（要人間判断）",
}


def format_file_line(thread: dict) -> str:
    path = thread.get("path") or "-"
    line = thread.get("line")
    if line:
        return f"`{path}:{line}`"
    return f"`{path}`"


def build_report(pr: dict, results: list[dict]) -> str:
    pr_number = pr.get("number", "?")
    pr_title = pr.get("title", "")
    lines = [
        "## pr-workflow:respond 実行予定 (dry-run)",
        "",
        f"PR #{pr_number}: {pr_title}",
        "",
        "| Thread ID | File:Line | 分類 | 予定アクション |",
        "|-----------|-----------|------|----------------|",
    ]

    for r in results:
        thread_id = r.get("thread_id", "?")
        category = r.get("category", "?")
        action = CATEGORY_ICONS.get(category, category)
        file_line = format_file_line(r)
        lines.append(f"| #{thread_id} | {file_line} | {category} | {action} |")

    if not results:
        lines.append("| — | — | — | 未返信スレッドなし |")

    lines += [
        "",
        "> **本実行するには** `--dry-run` を外して再度"
        " `/pr-workflow:respond` を実行してください。",
        "",
        "---",
        "_Generated by [pr-workflow:respond](https://github.com/UtakataKyosui/C2Lab)_",
    ]
    return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Post dry-run report as PR comment")
    parser.add_argument("--triage-file", required=True, help="Path to triage JSON")
    parser.add_argument("--pr", required=True, type=int, help="PR number")
    parser.add_argument(
        "--dry-run", action="store_true", help="Print report without posting"
    )
    args = parser.parse_args()

    triage_path = Path(args.triage_file)
    if not triage_path.is_file():
        print(json.dumps({"error": f"Triage file not found: {args.triage_file}"}))
        sys.exit(1)

    try:
        data = json.loads(triage_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}))
        sys.exit(1)

    pr_info = data.get("pr", {})
    results = data.get("results", [])

    report = build_report(pr_info, results)

    if args.dry_run:
        print(report)
        sys.exit(0)

    # Post as top-level PR summary comment (intentional use of gh pr comment)
    result = subprocess.run(  # noqa: S603
        ["gh", "pr", "comment", str(args.pr), "--body", report],
        capture_output=True,
        text=True,
        check=False,
    )

    if result.returncode != 0:
        print(json.dumps({"error": f"Failed to post comment: {result.stderr}"}))
        sys.exit(1)

    print(json.dumps({"success": True, "pr": args.pr, "report_length": len(report)}))


if __name__ == "__main__":
    main()
